baseURL = "https://www.datasketch.co/bid/datos-personales-y-leyes/"
languageCode = "es"
defaultContentLanguage = 'es'
title = "Los datos personales y sus leyes"
taxonomies = []
publishDir = "docs"

[languages]
[languages.es]
contentDir = "content/es"
languageName = "Español"
weight = 1
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 2
